### ISSUE TITLE
Code-env build is broken with new pip 20.3

### ISSUE THREAD

**Issue by alexcombessie** [Crowlingo/dss-crowlingo#3]
Hi @jonas92130 ,

The new pip introduced a breaking change in the dependency resolver mechanism: https://pip.pypa.io/en/latest/user_guide/#changes-to-the-pip-dependency-resolver-in-20-3-2020

Because of this, it is no longer possible to build the plugin code-env, it times out after 40 minutes trying to download all possible versions of numpy / idna.
[createPythonEnv_2020_12_22.log.gz](https://github.com/Crowlingo/dss-crowlingo/files/5729865/createPythonEnv_2020_12_22.log.gz)

Since this issue is linked to the dependency resolver of PyCrowlingo, could you update the package on pip and hardcode the new version number in the plugin requirements.txt?

Thanks,

Alex

**Comment by jonas92130** [comment]
Hi @alexcombessie, 

Thank you for sending me this information. I added the version to the PyCrowlingo dependency, but after testing, I find a new problem with pip: a conflict between requests==2.22.0 (Dataiku) and requests~=2.23.0 (PyCrowlingo). Do you know how to work around this problem without changing the requirements of the PyCrowlingo package? Here are the logs: 
[logs.log](https://github.com/Crowlingo/dss-crowlingo/files/5730175/logs.log)

Best,

Jonas

**Comment by alexcombessie** [comment]
Thanks for the swift response. Unfortunately, with the new pip dependency resolver, the only solution is to ensure both request requirements are equal. Is it feasible for your client library to use the same version? On our side, we cannot upgrade the requests version since it is hardcoded in our installation scripts and may have backcompatibility impacts.

**Comment by jonas92130** [comment]
Ok I changed the requirements on PyCrowlingo and dss-crowlingo it should be fine now. Thank you for your help.
